"""The benchmark's own annotation engine -- the gold set's writer, deliberately not the product's.

This code was ``spike/``. It was written as throwaway scaffolding to break the gate-2 circularity
(decision D-2), then frozen rather than deleted because ``spike/README.md`` recorded one reason it
could not go: *"``build_corpus.py`` is the only thing that can regenerate ``var/spike/corpus.yaml``,
and a measured gate whose corpus cannot be rebuilt is a measurement nobody can check."*

That reason is gone. :mod:`errata_ecosystem.corpusbuild` rebuilds the gate-2 corpus from production
code and reproduces the frozen file byte for byte, field for field, over all 1,426 records. What
remained in the spike afterwards was **not** scaffolding, and calling it scaffolding for another
six months would have been the mistake: it is the thing that writes the gold set, and a benchmark
needs one of those permanently.

**Why it lives here and stays separate from ``errata_audit``.** ``ecosystem/tools/build_gold.py``
says it plainly: *"a benchmark whose gold can only be regenerated by the code being benchmarked has
no independent gold."* R1 has its own layout and table modules -- better ones, with a cache, column
bands and a corrected born-digital rule -- and using them to write the answer key would make the
answer key an output of the system under test. So this is a second, independent implementation, and
its separateness is the point rather than an accident of history.

**It is frozen, and frozen now means something different.** Not "nobody is allowed to touch
scaffolding" but "this produced a published, hashed artifact". ``data/gold/manifest.json`` records
``layout_version: spike-layout/1.0.0`` and ``gold_version: spike-gold/1.0.0``, and those strings are
covered by the annotation files' own hashes. **The version constants therefore keep their original
values**, which reads oddly in a package no longer called ``spike`` and is correct: a version
identifies the algorithm that produced a hash, not the directory it was sitting in. Renaming them
would silently invalidate a published manifest to make a module look tidy.

**What R1 learned here and did NOT inherit.** Two findings were fixed in ``errata_audit`` and
deliberately not back-ported, because back-porting them would change the gold set:

* the "20 words per page" born-digital rule mislabels a thin but readable page as unreadable;
* nearest-token fallback fabricates a value when the window holds competing candidates (N12).

Both are wrong. Both stay, because this code's job is to reproduce the annotations that were
published, and an answer key that improves is an answer key that cannot be checked against
yesterday's numbers.
"""

from __future__ import annotations

from .attributes import ATTRIBUTES, TYPE_COLUMN, Attribute
from .gold import GOLD_VERSION, GoldRecord, build_gold
from .layout import LAYOUT_VERSION, TextLayer, Word, extract_layer
from .tables import TABLES_VERSION, Cell, Table, extract_tables, value_for_row

__all__ = [
    "ATTRIBUTES",
    "GOLD_VERSION",
    "LAYOUT_VERSION",
    "TABLES_VERSION",
    "TYPE_COLUMN",
    "Attribute",
    "Cell",
    "GoldRecord",
    "Table",
    "TextLayer",
    "Word",
    "build_gold",
    "extract_layer",
    "extract_tables",
    "value_for_row",
]
