"""FR-9.9 -- a leaderboard generated from the harness, including the rows where we lose.

The requirement has an unusual shape. Most benchmark tables are published by the system that wins
them; this one is required to be generated by the harness, with no hand-editing step, *because*
that is the only structural reason to believe the losing rows would still be there.

So there is no curation function in this module. :func:`leaderboard` takes the axis results and
the published figures and sorts them; :func:`losses` re-reads the same rows and lists every metric
where Errata is not first. Removing a losing row would mean removing a metric from the harness,
which is a visible edit to a file full of reasons why that would be dishonest.

**Two things this table is careful not to do.**

*It does not print 0.0 for a metric a system never reported.* ExtractBench's Table 3 does record
0.0 word-level grounding for systems that return no boxes -- that is a measured zero and it is
printed as one. But no other system reports compound-value normalization or calibrated abstention
at all, and rendering that as 0.0 would manufacture a win. Those cells read ``not scored``.

*It does not put our number and theirs in one column without saying they are different corpora.*
ExtractBench's 46.4% is over 370 documents across eight business domains; ours is over 1,426
fields from two low-voltage circuit-protection datasheets. Same metric, same threshold, different
population -- so the table carries the caveat on every row rather than in a footnote nobody reads.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from html import escape
from typing import Any

from errata_bench.operating_point import (
    EXTRACTBENCH_CITATION,
    EXTRACTBENCH_COST_CENTS_PER_PAGE,
    EXTRACTBENCH_PAGE_GROUNDING_F1,
    EXTRACTBENCH_SYSTEMS_AT_ZERO_GROUNDING,
    EXTRACTBENCH_SYSTEMS_EVALUATED,
    EXTRACTBENCH_VALUE_F1,
    EXTRACTBENCH_WORD_GROUNDING_F1,
    EXTRACTBENCH_WORD_GROUNDING_F1_REDUCTO,
    EXTRACTBENCH_WORD_GROUNDING_F1_SECOND,
)

from .axes import AxisResult, AxisStatus
from .reviewer import ReviewerReport

__all__ = [
    "CORPUS_CAVEAT",
    "Leaderboard",
    "Row",
    "leaderboard",
    "losses",
    "render_html",
    "render_json",
    "render_text",
]

NOT_SCORED = "not scored"
NOT_MEASURED = "NOT MEASURED"

CORPUS_CAVEAT = (
    "Same metric and threshold, different corpora. ExtractBench's figures are over its published "
    "set -- 370 documents, 4,869 pages, 67 document types, 8 business domains. Errata's are over "
    "1,426 fields from two low-voltage circuit-protection datasheets. A row of this table is "
    "comparable in definition and NOT in population, and no ranking here should be read as one "
    "system beating another on the other's data."
)


@dataclass(frozen=True, slots=True)
class Row:
    system: str
    origin: str
    """``published`` (read from the paper) or ``measured`` (produced by this harness now)."""

    word_grounding_f1: float | None = None
    page_grounding_f1: float | None = None
    value_f1: float | None = None
    extras: dict[str, Any] = field(default_factory=dict)
    note: str = ""

    @property
    def is_ours(self) -> bool:
        return self.system.startswith("Errata")

    def cell(self, metric: str) -> str:
        value = getattr(self, metric, None)
        if value is None:
            return NOT_SCORED
        return f"{value:.2f}"


@dataclass(frozen=True, slots=True)
class Leaderboard:
    rows: tuple[Row, ...]
    axes: tuple[AxisResult, ...]
    reviewer: ReviewerReport | None = None
    """FR-9.4 requires the evidence-acceptance rate to be reported *alongside* grounding F1. It
    is reported alongside it here as NOT MEASURED, which is the honest form of alongside."""

    caveat: str = CORPUS_CAVEAT
    citation: str = EXTRACTBENCH_CITATION.strip()

    def ranked(self, metric: str = "word_grounding_f1") -> tuple[Row, ...]:
        scored = [r for r in self.rows if getattr(r, metric, None) is not None]
        return tuple(sorted(scored, key=lambda r: getattr(r, metric), reverse=True))

    def our_rank(self, metric: str = "word_grounding_f1") -> tuple[int, int] | None:
        ranked = self.ranked(metric)
        for position, row in enumerate(ranked, start=1):
            if row.is_ours:
                return position, len(ranked)
        return None


def leaderboard(
    axes: tuple[AxisResult, ...], reviewer: ReviewerReport | None = None
) -> Leaderboard:
    """Build the table from axis results. The only place rows are created."""
    grounding = next((a for a in axes if a.axis == "grounding"), None)

    rows: list[Row] = [
        Row(
            system="LE Agentic Plus",
            origin="published",
            word_grounding_f1=EXTRACTBENCH_WORD_GROUNDING_F1,
            page_grounding_f1=EXTRACTBENCH_PAGE_GROUNDING_F1,
            value_f1=EXTRACTBENCH_VALUE_F1,
            note=f"{EXTRACTBENCH_COST_CENTS_PER_PAGE} c/page at the reported value accuracy",
        ),
        Row(
            system="LE Agentic",
            origin="published",
            word_grounding_f1=EXTRACTBENCH_WORD_GROUNDING_F1_SECOND,
            page_grounding_f1=66.1,
        ),
        Row(
            system="Reducto Deep",
            origin="published",
            word_grounding_f1=EXTRACTBENCH_WORD_GROUNDING_F1_REDUCTO,
            page_grounding_f1=71.7,
        ),
        Row(system="LE Cost-Eff.", origin="published", word_grounding_f1=40.4),
        Row(system="Extend Max", origin="published", word_grounding_f1=25.1),
        Row(system="Datalab A+B", origin="published", word_grounding_f1=2.0),
        Row(
            system="all other evaluated systems",
            origin="published",
            word_grounding_f1=0.0,
            note=(
                f"{EXTRACTBENCH_SYSTEMS_AT_ZERO_GROUNDING} of "
                f"{EXTRACTBENCH_SYSTEMS_EVALUATED} systems score 0.0 -- they return no "
                "word-level boxes at all. A measured zero, printed as one."
            ),
        ),
    ]

    if grounding is not None and grounding.status is AxisStatus.MEASURED:
        metrics = grounding.metrics
        rows.append(
            Row(
                system="Errata (R3 harness)",
                origin="measured",
                word_grounding_f1=_percent(metrics.get("word_grounding_f1")),
                page_grounding_f1=_percent(metrics.get("page_grounding_f1")),
                value_f1=_percent(metrics.get("value_f1")),
                extras={
                    "conservative_word_f1": metrics.get("conservative_word_f1"),
                    "n": grounding.n,
                },
                note=(
                    "measured now, by this harness, on the corpus named in the caveat. "
                    "Reproduce with: errata-r3 reproduce"
                ),
            )
        )
    else:
        rows.append(
            Row(
                system="Errata (R3 harness)",
                origin="measured",
                note="grounding axis NOT MEASURED -- no corpus present on this machine",
            )
        )

    return Leaderboard(rows=tuple(rows), axes=axes, reviewer=reviewer)


def _percent(text: Any) -> float | None:
    if text is None:
        return None
    if isinstance(text, (int, float)):
        return float(text)
    return float(str(text).rstrip("%"))


def losses(board: Leaderboard) -> tuple[str, ...]:
    """Every metric where somebody beats us, stated as a sentence. FR-9.9's actual content."""
    out: list[str] = []
    for metric, label in (
        ("word_grounding_f1", "word-level grounding F1 @ IoU 0.5"),
        ("page_grounding_f1", "page-level grounding F1"),
        ("value_f1", "value F1"),
    ):
        ranked = board.ranked(metric)
        if not ranked:
            continue
        ours = next((r for r in ranked if r.is_ours), None)
        best = ranked[0]
        if ours is None:
            continue
        if best.is_ours:
            continue
        gap = getattr(best, metric) - getattr(ours, metric)
        out.append(
            f"{label}: {best.system} {getattr(best, metric):.2f} beats Errata "
            f"{getattr(ours, metric):.2f} by {gap:.2f}pp"
        )

    for axis in board.axes:
        if axis.status is AxisStatus.NOT_MEASURED:
            out.append(f"{axis.axis}: NOT MEASURED -- {axis.headline}")
    if board.reviewer is not None and not board.reviewer.measured:
        out.append(
            "evidence-acceptance rate (FR-9.4) and reviewer-seconds (FR-9.3): NOT MEASURED -- "
            + board.reviewer.reason
        )
    return tuple(out)


def render_text(board: Leaderboard) -> str:
    lines = [
        "ERRATA BENCHMARK -- LEADERBOARD (FR-9.9)",
        "=" * 96,
        "",
        f"{'system':<30}{'origin':<11}{'word F1':>12}{'page F1':>12}{'value F1':>12}",
        "-" * 96,
    ]
    for row in board.ranked("word_grounding_f1"):
        lines.append(
            f"{row.system:<30}{row.origin:<11}"
            f"{row.cell('word_grounding_f1'):>12}"
            f"{row.cell('page_grounding_f1'):>12}"
            f"{row.cell('value_f1'):>12}"
        )
    unranked = [r for r in board.rows if r.word_grounding_f1 is None]
    for row in unranked:
        lines.append(f"{row.system:<30}{row.origin:<11}{NOT_SCORED:>12}")

    rank = board.our_rank()
    lines += ["", "WHERE WE LOSE", "-" * 96]
    for sentence in losses(board):
        lines.append(f"  {sentence}")
    if rank:
        lines.append(f"  rank on word-level grounding F1: {rank[0]} of {rank[1]}")

    lines += ["", "AXES NO OTHER SYSTEM REPORTS", "-" * 96]
    for axis in board.axes:
        if axis.axis == "grounding":
            continue
        lines.append(f"  {axis.axis:<20} {axis.status.value:<14} {axis.headline}")

    lines += ["", "THE TWO HUMAN NUMBERS (FR-9.3, FR-9.4)", "-" * 96]
    if board.reviewer is None:
        lines.append("  no reviewer report supplied to this render")
    else:
        for line in board.reviewer.text().splitlines():
            lines.append("  " + line)

    lines += ["", "READ THIS BEFORE READING THE TABLE", "-" * 96]
    for chunk in _wrap(board.caveat):
        lines.append("  " + chunk)
    lines += ["", board.citation]
    return "\n".join(lines)


def render_json(board: Leaderboard) -> str:
    return json.dumps(
        {
            "leaderboard": [
                {
                    "system": r.system,
                    "origin": r.origin,
                    "word_grounding_f1": r.word_grounding_f1,
                    "page_grounding_f1": r.page_grounding_f1,
                    "value_f1": r.value_f1,
                    "note": r.note,
                    "extras": r.extras,
                }
                for r in board.ranked("word_grounding_f1")
            ],
            "our_rank_word_grounding_f1": board.our_rank(),
            "losses": list(losses(board)),
            "reviewer": board.reviewer.as_dict() if board.reviewer else None,
            "axes": [a.as_dict() for a in board.axes],
            "caveat": board.caveat,
            "citation": board.citation,
        },
        indent=2,
    )


def render_html(board: Leaderboard) -> str:
    def cells(row: Row) -> str:
        klass = ' class="ours"' if row.is_ours else ""
        return (
            f"<tr{klass}><td>{escape(row.system)}</td><td>{escape(row.origin)}</td>"
            f"<td class=n>{escape(row.cell('word_grounding_f1'))}</td>"
            f"<td class=n>{escape(row.cell('page_grounding_f1'))}</td>"
            f"<td class=n>{escape(row.cell('value_f1'))}</td>"
            f"<td>{escape(row.note)}</td></tr>"
        )

    rows = "\n".join(cells(r) for r in board.ranked("word_grounding_f1"))
    loss_items = "\n".join(f"<li>{escape(s)}</li>" for s in losses(board))
    axis_rows = "\n".join(
        f"<tr><td>{escape(a.axis)}</td><td>{escape(a.requirement)}</td>"
        f"<td>{escape(a.status.value)}</td><td>{escape(a.headline)}</td></tr>"
        for a in board.axes
    )
    return f"""<!doctype html>
<meta charset="utf-8">
<title>Errata benchmark leaderboard</title>
<style>
 body {{ font: 15px/1.5 system-ui, sans-serif; margin: 2rem auto; max-width: 62rem; color: #111; }}
 table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
 th, td {{ border-bottom: 1px solid #ddd; padding: .4rem .6rem; text-align: left; }}
 td.n {{ text-align: right; font-variant-numeric: tabular-nums; }}
 tr.ours {{ background: #fff6e5; font-weight: 600; }}
 .caveat {{ background: #fdf3f3; border-left: 4px solid #c0392b; padding: .8rem 1rem; }}
</style>
<h1>Errata benchmark leaderboard</h1>
<p class=caveat><strong>Read this first.</strong> {escape(board.caveat)}</p>
<table>
<tr><th>system</th><th>origin</th><th>word F1</th><th>page F1</th><th>value F1</th><th>note</th></tr>
{rows}
</table>
<h2>Where we lose</h2>
<ul>
{loss_items}
</ul>
<h2>The two human numbers</h2>
<pre>{escape(board.reviewer.text()) if board.reviewer else "no reviewer report supplied"}</pre>
<h2>Axes no other system reports</h2>
<table>
<tr><th>axis</th><th>requirement</th><th>status</th><th>result</th></tr>
{axis_rows}
</table>
<p>{escape(board.citation)}</p>
<p><em>Generated by errata-r3 leaderboard. There is no hand-editing step (FR-9.9).</em></p>
"""


def _wrap(text: str, width: int = 92) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines
