"""Fixtures for the R1 tests.

**The PDFs are built here rather than committed.** ``.gitignore`` excludes ``*.pdf`` (FR-9.5:
distribute URLs and hashes, never payloads), so a test that depended on a committed datasheet would
pass on the author's machine and fail on a clean clone -- the exact failure mode this repository
has already been careful about elsewhere. Every fixture below is generated by PyMuPDF at test time
from a literal description, which also means each one exercises a *named* document shape:

* ``ordering_table_pdf`` -- the well-formed case: a ruled table with a type column.
* ``merged_cell_pdf`` -- one cell spanning a block of rows, the ABB S200 pole-count shape.
* ``two_column_pdf`` -- two products side by side, the FR-1.6 bleed case.
* ``scanned_pdf`` -- a page with no text layer at all.

The real ABB datasheets are used where a test genuinely needs a real document, and those tests
**skip** when the corpus has not been fetched rather than failing.
"""

from __future__ import annotations

from pathlib import Path

import pymupdf
import pytest

from errata_audit.documents import BlobStore, DocumentSource, ingest_document
from errata_spec import DocumentRegister

REPO_ROOT = Path(__file__).resolve().parents[2]
# `var/spike/` is a historical name and deliberately not renamed. It is gitignored working
# data whose location is declared by `data/reference/manifest.json` and hashed into the R3
# reproduction receipt; renaming it would force every existing checkout to re-fetch and would
# move a published receipt, to correct a directory name nobody types. The `spike/` PACKAGE is
# gone (see audit/tests/test_boundaries.py); this is just where its documents landed.
DATASHEETS = REPO_ROOT / "var" / "spike" / "datasheets"
ABB_S200 = DATASHEETS / "abb-s200-2CDC002142D0207.pdf"
ABB_S200_MUC = DATASHEETS / "abb-s200muc-1SXP403008B0202.pdf"
ETIM_DIR = REPO_ROOT / "var" / "reference" / "etim"


def _grid(page, cols: list[float], rows: list[float]) -> None:
    for x in cols:
        page.draw_line((x, rows[0]), (x, rows[-1]))
    for y in rows:
        page.draw_line((cols[0], y), (cols[-1], y))


@pytest.fixture
def ordering_table_pdf(tmp_path: Path) -> Path:
    """A ruled ordering table: Type / Rated current / Packing unit / Weight."""
    document = pymupdf.open()
    page = document.new_page(width=460, height=300)
    cols = [30, 130, 240, 350, 440]
    rows = [60, 92, 124, 156]
    _grid(page, cols, rows)
    table = [
        ["Type", "Rated current I n A", "Packing unit PCS", "Weight 1 PC kg"],
        ["AX-10", "10", "5", "0.125"],
        ["AX-16", "16", "5", "0.125"],
    ]
    for r, row in enumerate(table):
        for c, value in enumerate(row):
            page.insert_text((cols[c] + 4, rows[r] + 18), value, fontsize=8)
    path = tmp_path / "ordering.pdf"
    document.save(path)
    return path


@pytest.fixture
def merged_cell_pdf(tmp_path: Path) -> Path:
    """A pole-count column stated once for a block of three rows -- merged by geometry."""
    document = pymupdf.open()
    page = document.new_page(width=460, height=300)
    cols = [30, 130, 250, 440]
    rows = [60, 92, 124, 156]
    # The pole column's vertical rules stop after the header, so the cell spans the block.
    for y in rows:
        page.draw_line((cols[0], y), (cols[-1], y)) if y in (rows[0], rows[1], rows[-1]) else page.draw_line((cols[1], y), (cols[-1], y))
    page.draw_line((cols[0], rows[0]), (cols[0], rows[-1]))
    page.draw_line((cols[1], rows[0]), (cols[1], rows[-1]))
    page.draw_line((cols[2], rows[0]), (cols[2], rows[-1]))
    page.draw_line((cols[3], rows[0]), (cols[3], rows[-1]))

    page.insert_text((cols[0] + 4, rows[0] + 18), "Number of poles", fontsize=7)
    page.insert_text((cols[1] + 4, rows[0] + 18), "Type", fontsize=7)
    page.insert_text((cols[2] + 4, rows[0] + 18), "Rated current I n A", fontsize=7)
    page.insert_text((cols[0] + 4, rows[1] + 18), "1", fontsize=8)
    for index, (sku, current) in enumerate((("AX-10", "10"), ("AX-16", "16"))):
        y = rows[1 + index]
        page.insert_text((cols[1] + 4, y + 18), sku, fontsize=8)
        page.insert_text((cols[2] + 4, y + 18), current, fontsize=8)
    path = tmp_path / "merged.pdf"
    document.save(path)
    return path


@pytest.fixture
def two_column_pdf(tmp_path: Path) -> Path:
    """Two products side by side with a wide gutter -- the FR-1.6 cross-bleed case."""
    document = pymupdf.open()
    page = document.new_page(width=600, height=300)
    page.insert_text((40, 80), "AX-10", fontsize=10)
    page.insert_text((40, 100), "Rated current 10 A", fontsize=9)
    page.insert_text((400, 80), "AX-63", fontsize=10)
    page.insert_text((400, 100), "Rated current 63 A", fontsize=9)
    path = tmp_path / "two-column.pdf"
    document.save(path)
    return path


@pytest.fixture
def scanned_pdf(tmp_path: Path) -> Path:
    """A page with no usable text layer. The audit must decline, never guess."""
    document = pymupdf.open()
    page = document.new_page(width=400, height=300)
    page.draw_rect(pymupdf.Rect(20, 20, 380, 280), color=(0.8, 0.8, 0.8))
    path = tmp_path / "scan.pdf"
    document.save(path)
    return path


@pytest.fixture
def register() -> DocumentRegister:
    return DocumentRegister()


@pytest.fixture
def store(tmp_path: Path) -> BlobStore:
    return BlobStore(tmp_path / "blobs")


@pytest.fixture
def source_of(register: DocumentRegister, store: BlobStore):
    def _make(path: Path, *, doc_id: str = "") -> DocumentSource:
        return ingest_document(path, register=register, store=store, doc_id=doc_id)

    return _make


def etim_archive() -> Path | None:
    if not ETIM_DIR.exists():
        return None
    extracted = ETIM_DIR / "extracted"
    if (extracted / "ETIMARTCLASS.csv").exists():
        return extracted
    archives = sorted(p for p in ETIM_DIR.glob("*.zip") if not p.name.startswith("_"))
    return archives[0] if archives else None


requires_etim = pytest.mark.skipif(
    etim_archive() is None,
    reason="ETIM 10.0 not fetched; run scripts/fetch_reference_data.sh (free, ODC-By, no login)",
)

requires_datasheets = pytest.mark.skipif(
    not ABB_S200.exists(),
    reason="the ABB datasheets are not committed (FR-9.5); run scripts/fetch_reference_data.sh",
)
