/**
 * The surfaces under test, in one place.
 *
 * Every spec iterates this list rather than hard-coding paths, so a new page
 * gets smoke-tested, axe-tested and screenshot-diffed by being added here once.
 * The register's §3 records nine specified pages that were never built; when
 * they are, this is the list they join, and nothing else needs editing.
 */

export interface Surface {
  /** Stable id — used for screenshot filenames, so changing it orphans baselines. */
  id: string;
  path: string;
  /** Something that must be on the page for it to count as loaded. */
  expect: { role?: 'heading'; text?: string; selector?: string };
  /** Pages whose whole job is a WebGL scene; the heavy 3D specs only run on these. */
  scene?: boolean;
}

export const SURFACES: Surface[] = [
  {
    id: 'datum-index',
    path: '/web/datum/index.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'datum-grid',
    path: '/web/datum/grid.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'datum-room-i',
    path: '/web/datum/room-i.html',
    expect: { selector: '#hero-line' },
  },
  {
    // §13.5 designates this page as THE CI screenshot-diff target. It has 21
    // components in every state, and until now nothing had ever diffed it.
    id: 'datum-states',
    path: '/web/datum/states.html',
    expect: { selector: 'body' },
  },
  {
    id: 'console',
    path: '/web/console/index.html',
    expect: { selector: 'body' },
  },
  {
    id: 'site-index',
    path: '/web/site/index.html',
    expect: { selector: '#hero-line' },
  },
  // The pages the register listed as specified-but-never-built. Generated by web/site/build.py
  // from one shell, so adding one here is the only edit a new page needs to be smoke-tested,
  // axe-tested and keyboard-tested.
  {
    id: 'site-method',
    path: '/web/site/method.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-benchmark',
    path: '/web/site/benchmark.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-errata',
    path: '/web/site/errata.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-pricing',
    path: '/web/site/pricing.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-docs',
    path: '/web/site/docs.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-404',
    path: '/web/site/404.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-500',
    path: '/web/site/500.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'landing',
    path: '/web/landing/index.html',
    expect: { selector: 'body' },
    scene: true,
  },
];

/**
 * Requests that are allowed to fail, by name.
 *
 * **This list used to hold all three type families and now holds one file.** The
 * fonts landed on 22 August 2026 (`web/datum/fonts/README.md` carries the
 * acquisition log), so ten of the eleven declared faces now resolve and a 404 on
 * any of them is a real failure.
 *
 * The survivor is `Sligoil-Regular.woff2`, which the foundry's current release
 * does not contain. It is NOT mapped to Sligoil Micro — a different face — so the
 * declaration stays, the file stays absent, and the exception stays written down
 * here rather than the assertion being loosened. ADR-006 records the decision it
 * needs; when that lands, this list goes to empty.
 */
export const KNOWN_MISSING = [/Sligoil-Regular\.woff2/i];

export function isKnownMissing(url: string): boolean {
  return KNOWN_MISSING.some((pattern) => pattern.test(url));
}
