/**
 * The surfaces under test, in one place.
 *
 * Every spec iterates this list rather than hard-coding paths, so a new page
 * gets smoke-tested, axe-tested and screenshot-diffed by being added here once.
 * The register's §3 records nine specified pages that were never built; when
 * they are, this is the list they join, and nothing else needs editing.
 */

export interface Surface {
  /** Stable id — used for screenshot filenames, so changing it orphans baselines. */
  id: string;
  path: string;
  /** Something that must be on the page for it to count as loaded. */
  expect: { role?: 'heading'; text?: string; selector?: string };
  /** Pages whose whole job is a WebGL scene; the heavy 3D specs only run on these. */
  scene?: boolean;
}

export const SURFACES: Surface[] = [
  {
    id: 'datum-index',
    path: '/web/datum/index.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'datum-grid',
    path: '/web/datum/grid.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'datum-room-i',
    path: '/web/datum/room-i.html',
    expect: { selector: '#hero-line' },
  },
  {
    // §13.5 designates this page as THE CI screenshot-diff target. It has 21
    // components in every state, and until now nothing had ever diffed it.
    id: 'datum-states',
    path: '/web/datum/states.html',
    expect: { selector: 'body' },
  },
  {
    id: 'console',
    path: '/web/console/index.html',
    expect: { selector: 'body' },
  },
  {
    id: 'site-index',
    path: '/web/site/index.html',
    expect: { selector: '#hero-line' },
  },
  // The pages the register listed as specified-but-never-built. Generated by web/site/build.py
  // from one shell, so adding one here is the only edit a new page needs to be smoke-tested,
  // axe-tested and keyboard-tested.
  {
    id: 'site-method',
    path: '/web/site/method.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-benchmark',
    path: '/web/site/benchmark.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-errata',
    path: '/web/site/errata.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-pricing',
    path: '/web/site/pricing.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-docs',
    path: '/web/site/docs.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-404',
    path: '/web/site/404.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'site-500',
    path: '/web/site/500.html',
    expect: { selector: 'h1' },
  },
  {
    id: 'landing',
    path: '/web/landing/index.html',
    expect: { selector: 'body' },
    scene: true,
  },
];

/**
 * Requests that are allowed to fail, by name, with an expiry condition.
 *
 * The three type families specified in blueprint §5.2 are not in the repository
 * (`web/datum/fonts/README.md`), so every page requests them and every request
 * 404s. That is a known, recorded, open item — FE-1 O-1, the oldest in the
 * project — and failing the smoke suite on it would mean the suite is red from
 * the day it is written, which is how a suite gets ignored.
 *
 * **This list is deleted when the fonts land.** At that point a missing font
 * becomes a test failure rather than a known exception, which is the whole
 * point of writing the exception down instead of loosening the assertion.
 */
export const KNOWN_MISSING = [/\/fonts\/redaction\//i, /\/fonts\/apfel\//i, /\/fonts\/sligoil\//i];

export function isKnownMissing(url: string): boolean {
  return KNOWN_MISSING.some((pattern) => pattern.test(url));
}
